language: go
sudo: false

go:
  - '1.8.x'
  - '1.9.x'
  - '1.10.x'
  - '1.11.x'
  - '1.12.x'
  - 'tip'

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - go vet ./...
  - test -z "$(gofmt -d -s . | tee /dev/stderr)"
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
